### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by gaukas** [NeToucher/WHMCS_AlipayF2F#1]
To construct the refund function of F2Fpay (Face2face).
The currency of $amount is USD in WHMCS, but for Alipay it is CNY. So we are using the fixed currency 7. When posting out the $amount, it should be $amount_in_WHMCS*7.00. And when you get the callback, $amount=$callback_amount/7.00

**Comment by Leginion** [comment]
Finished: https://github.com/NeToucher/WHMCS_AlipayF2F/commit/1b5577accb2cf91c5550d7065bd92688f929ebdb
